CREATE TABLE T09D_AFASTAMENTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INICIO DATE NOT NULL,
    TERMINO DATE NOT NULL,
    ID_TIPO INTEGER NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    CONSTRAINT T09D_AFASTAMENTO_FK FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID),
    CONSTRAINT T09D_AFASTAMENTO_FKTIPO FOREIGN KEY (ID_TIPO) REFERENCES T09D_TIPO_AFASTAMENTO (ID)
);

CREATE TABLE T09D_AJUSTE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_LANCAMENTO DATE NOT NULL,
    QUANTIDADE_HORAS NUMBER(6,2) NOT NULL,
    MOTIVO VARCHAR2(200) NOT NULL,
    ID_TIPO_AJUSTE INTEGER NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    CONSTRAINT T09D_AJUSTE_FKPROF FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID),
    CONSTRAINT T09D_AJUSTE_FKTIPO FOREIGN KEY (ID_TIPO_AJUSTE) REFERENCES T09D_TIPO_AJUSTE (ID)
);

CREATE TABLE T09D_BAIRRO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL UNIQUE,
    MUNICIPIO VARCHAR2(50) NOT NULL,
    SIGLA_UF CHAR(2) NOT NULL
);

CREATE TABLE T09D_BANCO_DE_HORAS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_BANCO DATE NOT NULL,
    SALDO_HORA NUMBER(6,2) NOT NULL,
    ID_REGISTRO_PONTO INTEGER NOT NULL,
	ID_COMPENSACAO INTEGER NOT NULL,
	CONSTRAINT T09D_BANCO_DE_HORAS_FKCOMP FOREIGN KEY (ID_COMPENSACAO) REFERENCES T09D_COMPENSACAO (ID),
    CONSTRAINT T09D_BANCO_DE_HORAS_FKPON FOREIGN KEY (ID_REGISTRO_PONTO) REFERENCES T09D_REGISTRO_DE_PONTO (ID)
);

CREATE TABLE T09D_COMPENSACAO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_COMPENSACAO DATE NOT NULL,
    HORAS_USADAS NUMBER(6,2) NOT NULL,
    JUSTIFICATIVA VARCHAR2(200) NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    CONSTRAINT T09D_COMPENSACAO_FK2 FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID)
);

CREATE TABLE T09D_CONTRATO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPRESA_CONTRATANTE VARCHAR2(100) NOT NULL,
    INICIO DATE NOT NULL,
    TERMINO DATE NULL,
    DATA_ADMISSAO DATE NOT NULL,
    ATIVO INTEGER NOT NULL,
    CARGA_HORARIA_SEMANAL NUMBER(5,2) NOT NULL,
    VALOR_MENSAL NUMBER(10,2) NOT NULL,
    ID_TIPO_CONTRATO INTEGER NOT NULL,
    ID_TIPO_JORNADA INTEGER NOT NULL,
    CONSTRAINT T09D_CONTRATO_FKJORNADA FOREIGN KEY (ID_TIPO_JORNADA) REFERENCES T09D_TIPO_JORNADA (ID),
    CONSTRAINT T09D_CONTRATO_FKCONTRATO FOREIGN KEY (ID_TIPO_CONTRATO) REFERENCES T09D_TIPO_CONTRATO (ID)
);

CREATE TABLE T09D_ENDERECO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOGRADOURO VARCHAR2(50) NOT NULL,
    COMPLEMENTO VARCHAR2(100),
    NUMERO_CASA INTEGER NOT NULL,
    NUMERO_CEP INTEGER NOT NULL,
    ID_BAIRRO INTEGER NOT NULL,
    CONSTRAINT T09D_ENDERECO_FK FOREIGN KEY (ID_BAIRRO) REFERENCES T09D_BAIRRO (ID)
);

CREATE TABLE T09D_ESCALA (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_SEMANA DATE NOT NULL,
    INICIO TIMESTAMP NOT NULL,
    TERMINO TIMESTAMP NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    CONSTRAINT T09D_ESCALA_FK FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID)
);

CREATE TABLE T09D_ESPECIALIZACAO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE T09D_EVENTO_PAGAMENTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(200),
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    ID_RUBRICA INTEGER NOT NULL,
    ID_REGISTRO_PONTO INTEGER NOT NULL,
    ID_BANCO_HORAS INTEGER NOT NULL,
    ID_AFASTAMENTO INTEGER NOT NULL,
    CONSTRAINT T09D_EVENTO_PAGAMENTO_FKAFAS FOREIGN KEY (ID_AFASTAMENTO) REFERENCES T09D_AFASTAMENTO (ID),
    CONSTRAINT T0D9_EVENTO_PAGAMENTO_FKBANC FOREIGN KEY (ID_BANCO_HORAS) REFERENCES T09D_BANCO_DE_HORAS (ID),
    CONSTRAINT T09D_EVENTO_PAGAMENTO_FKFORM FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES T09D_FORMA_DE_PAGAMENTO (ID),
    CONSTRAINT T09D_EVENTO_PAGAMENTO_FKPON FOREIGN KEY (ID_REGISTRO_PONTO) REFERENCES T09D_REGISTRO_DE_PONTO (ID),
    CONSTRAINT T09D_EVENTO_PAGAMENTO_FK_RUB FOREIGN KEY (ID_RUBRICA) REFERENCES T09D_RUBRICA (ID)
);

CREATE TABLE T09D_FERIAS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INICIO DATE NOT NULL,
    FIM DATE NOT NULL,
    SALDO_DIAS NUMBER(5,2) NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    CONSTRAINT T09D_FERIAS_FKPROF FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID)
);

CREATE TABLE T09D_FORMACAO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL,
    INSTITUICAO VARCHAR2(100) NOT NULL,
    INICIO DATE NOT NULL,
    FIM DATE NOT NULL,
    NIVEL VARCHAR2(100),
    ID_PROFISSIONAL INTEGER NOT NULL,
    CONSTRAINT T09D_FORMACAO_FKPROF FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID)
);

CREATE TABLE T09D_FORMA_DE_PAGAMENTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE T09D_NIVEL_DE_ACESSO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(200) NOT NULL UNIQUE
);

CREATE TABLE T09D_OCUPACAO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_LEITO INTEGER NOT NULL UNIQUE,
    ENTRADA DATE NOT NULL,
    SAIDA DATE,
    ID_PROFISSIONAL INTEGER NOT NULL,
    ID_PACIENTE INTEGER NOT NULL,
    CONSTRAINT T09D_OCUPACAO_FKPROF FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID),
    CONSTRAINT T09D_OCUPACAO_FKPAC FOREIGN KEY (ID_PACIENTE) REFERENCES T09D_PACIENTE (ID)
);

CREATE TABLE T09D_PACIENTE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ENTRADA DATE NOT NULL,
    SAIDA DATE,
    SITUACAO VARCHAR2(100) NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    CONSTRAINT T09D_PACIENTE_FKPROF FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID)
);

CREATE TABLE T09D_PONTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_REGISTRO DATE NOT NULL,
    REGISTRO TIMESTAMP NOT NULL,
    ID_TIPO_PONTO INTEGER NOT NULL,
    CONSTRAINT T09D_PONTO_FK FOREIGN KEY (ID_TIPO_PONTO) REFERENCES T09D_TIPO_PONTO (ID)
);

CREATE TABLE T09D_PROFISSIONAL (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(200) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    CRM VARCHAR2(50) UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    ID_ENDERECO INTEGER NOT NULL,
    ID_SETOR INTEGER NOT NULL,
    ID_CONTRATO INTEGER NOT NULL,
    ID_NIVEL_ACESSO INTEGER NOT NULL,
    CONSTRAINT T09D_PROFISSIONAL_FKCONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES T09D_CONTRATO (ID),
    CONSTRAINT T09D_PROFISSIONAL_FKENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES T09D_ENDERECO (ID),
    CONSTRAINT T09D_PROFISSIONAL_FKACES FOREIGN KEY (ID_NIVEL_ACESSO) REFERENCES T09D_NIVEL_DE_ACESSO (ID),
    CONSTRAINT T09D_PROFISSIONAL_FKSET FOREIGN KEY (ID_SETOR) REFERENCES T09D_SETOR (ID)
);

CREATE TABLE T09D_PROFISSIONAL_ESPEC (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PROFISSIONAL INTEGER NOT NULL,
    ID_ESPECIALIZACAO INTEGER NOT NULL,
    CONSTRAINT T09D_PROFISSIONAL_ESPEC_FKPROF FOREIGN KEY (ID_ESPECIALIZACAO) REFERENCES T09D_ESPECIALIZACAO (ID),
    CONSTRAINT T09D_PROFISSIONAL_ESPEC_FKESPEC FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID)
);

CREATE TABLE T09D_REGISTRO_DE_PONTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_REGISTRO DATE NOT NULL,
    OBSERVACOES VARCHAR2(200),
    ID_AJUSTE INTEGER NOT NULL,
    ID_COMPENSACAO INTEGER NOT NULL,
    ID_PONTO INTEGER NOT NULL,
    ID_PROFISSIONAL INTEGER NOT NULL,
    ID_ESCALA INTEGER NOT NULL,
    ID_FERIAS INTEGER NOT NULL,
    CONSTRAINT T09D_REGISTRO_PONTO_FKESCA FOREIGN KEY (ID_ESCALA) REFERENCES T09D_ESCALA (ID),
    CONSTRAINT T09D_REGISTRO_PONTO_FKFERIAS FOREIGN KEY (ID_FERIAS) REFERENCES T09D_FERIAS (ID),
    CONSTRAINT T09D_REGISTRO_DE_PONTO_FKPROF FOREIGN KEY (ID_PROFISSIONAL) REFERENCES T09D_PROFISSIONAL (ID),
    CONSTRAINT T09D_REGISTRO_DE_PONTO_FKPONT FOREIGN KEY (ID_PONTO) REFERENCES T09D_PONTO (ID),
    CONSTRAINT T09D_REGISTRO_DE_PONTO_FKAJU FOREIGN KEY (ID_AJUSTE) REFERENCES T09D_AJUSTE (ID),
    CONSTRAINT T09D_REGISTRO_DE_PONTO_FKCOMP FOREIGN KEY (ID_COMPENSACAO) REFERENCES T09D_COMPENSACAO (ID)
);

CREATE TABLE T09D_RUBRICA (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(200) NOT NULL UNIQUE,
    ID_TIPO_RUBRICA INTEGER NOT NULL,
    CONSTRAINT T09D_RUBRICA_FK FOREIGN KEY (ID_TIPO_RUBRICA) REFERENCES T09D_TIPO_RUBRICA (ID)
);

CREATE TABLE T09D_SETOR (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE T09D_TIPO_AFASTAMENTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE T09D_TIPO_AJUSTE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(200) NOT NULL UNIQUE
);

CREATE TABLE T09D_TIPO_CONTRATO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE T09D_TIPO_JORNADA (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE T09D_TIPO_PONTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE T09D_TIPO_RUBRICA (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO_TIPO VARCHAR2(200) NOT NULL UNIQUE
); 