-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2025-05-08 12:50:04.017

-- foreign keys
ALTER TABLE T09D_AFASTAMENTO
    DROP CONSTRAINT AFASTAMENTO_PROFISSIONAL;

ALTER TABLE T09D_COMPENSACAO
    DROP CONSTRAINT COMPENSACAO_BANCO_HORAS;

ALTER TABLE T09D_COMPENSACAO
    DROP CONSTRAINT COMPENSACAO_PROFISSIONAL;

ALTER TABLE T09D_CONTRATO
    DROP CONSTRAINT CONTRATO_JORNADA;

ALTER TABLE T09D_CONTRATO
    DROP CONSTRAINT CONTRATO_TIPO_CONTRATO;

ALTER TABLE T09D_EVENTO_PAGAMENTO
    DROP CONSTRAINT EVENTO_PAGAMENTO_AFASTAMENTO;

ALTER TABLE T09D_EVENTO_PAGAMENTO
    DROP CONSTRAINT EVENTO_PAGAMENTO_BANCO;

ALTER TABLE T09D_FORMACAO
    DROP CONSTRAINT FORMACAO_PROFISSIONAL;

ALTER TABLE T09D_OCUPACAO
    DROP CONSTRAINT OCUPACAO_PROFISSIONAL;

ALTER TABLE T09D_PACIENTE
    DROP CONSTRAINT PACIENTE_PROFISSIONAL;

ALTER TABLE T09D_PONTO
    DROP CONSTRAINT PONTO_TIPO_PONTO;

ALTER TABLE T09D_PROFISSIONAL
    DROP CONSTRAINT PROFISSIONAL_CONTRATO;

ALTER TABLE T09D_PROFISSIONAL
    DROP CONSTRAINT PROFISSIONAL_ENDERECO;

ALTER TABLE T09D_PROFISSIONAL_ESPEC
    DROP CONSTRAINT PROFISSIONAL_ESPECIALIZACAO;

ALTER TABLE T09D_PROFISSIONAL_ESPEC
    DROP CONSTRAINT PROFISSIONAL_ESPEC_PROF;

ALTER TABLE T09D_PROFISSIONAL
    DROP CONSTRAINT PROFISSIONAL_NIVEL_DE_ACESSO;

ALTER TABLE T09D_REGISTRO_DE_PONTO
    DROP CONSTRAINT REGISTRO_DE_PONTO_ESCALA;

ALTER TABLE T09D_REGISTRO_DE_PONTO
    DROP CONSTRAINT REGISTRO_DE_PONTO_FERIAS;

ALTER TABLE T09D_REGISTRO_DE_PONTO
    DROP CONSTRAINT REGISTRO_DE_PONTO_PROFISSIONAL;

ALTER TABLE T09D_AJUSTE
    DROP CONSTRAINT T09D_AJUSTE_T09D_PROFISSIONAL;

ALTER TABLE T09D_AJUSTE
    DROP CONSTRAINT T09D_AJUSTE_T09D_TIPO_AJUSTE;

ALTER TABLE T09D_ENDERECO
    DROP CONSTRAINT T09D_ENDERECO_T09D_BAIRRO;

ALTER TABLE T09D_ESCALA
    DROP CONSTRAINT T09D_ESCALA_T09D_PROFISSIONAL;

ALTER TABLE T09D_FERIAS
    DROP CONSTRAINT T09D_FERIAS_T09D_PROFISSIONAL;

ALTER TABLE T09D_OCUPACAO
    DROP CONSTRAINT T09D_OCUPACAO_T09D_PACIENTE;

ALTER TABLE T09D_PROFISSIONAL
    DROP CONSTRAINT T09D_PROFISSIONAL_T09D_SETOR;

ALTER TABLE T09D_RUBRICA
    DROP CONSTRAINT T09D_RUBRICA_T09D_TIPO_RUBRICA;

ALTER TABLE T09D_AFASTAMENTO
    DROP CONSTRAINT afastamento_tipo_afastamento;

ALTER TABLE T09D_BANCO_DE_HORAS
    DROP CONSTRAINT banco_horas_registro_ponto;

ALTER TABLE T09D_EVENTO_PAGAMENTO
    DROP CONSTRAINT evento_forma_pagamento;

ALTER TABLE T09D_EVENTO_PAGAMENTO
    DROP CONSTRAINT evento_pagamento_reg_ponto;

ALTER TABLE T09D_EVENTO_PAGAMENTO
    DROP CONSTRAINT evento_pagamento_rubrica;

ALTER TABLE T09D_REGISTRO_DE_PONTO
    DROP CONSTRAINT ponto_registro_ponto;

ALTER TABLE T09D_REGISTRO_DE_PONTO
    DROP CONSTRAINT registro_ponto_ajuste;

ALTER TABLE T09D_REGISTRO_DE_PONTO
    DROP CONSTRAINT registro_ponto_compensacao;

-- tables
DROP TABLE T09D_AFASTAMENTO;

DROP TABLE T09D_AJUSTE;

DROP TABLE T09D_BAIRRO;

DROP TABLE T09D_BANCO_DE_HORAS;

DROP TABLE T09D_COMPENSACAO;

DROP TABLE T09D_CONTRATO;

DROP TABLE T09D_ENDERECO;

DROP TABLE T09D_ESCALA;

DROP TABLE T09D_ESPECIALIZACAO;

DROP TABLE T09D_EVENTO_PAGAMENTO;

DROP TABLE T09D_FERIAS;

DROP TABLE T09D_FORMACAO;

DROP TABLE T09D_FORMA_DE_PAGAMENTO;

DROP TABLE T09D_NIVEL_DE_ACESSO;

DROP TABLE T09D_OCUPACAO;

DROP TABLE T09D_PACIENTE;

DROP TABLE T09D_PONTO;

DROP TABLE T09D_PROFISSIONAL;

DROP TABLE T09D_PROFISSIONAL_ESPEC;

DROP TABLE T09D_REGISTRO_DE_PONTO;

DROP TABLE T09D_RUBRICA;

DROP TABLE T09D_SETOR;

DROP TABLE T09D_TIPO_AFASTAMENTO;

DROP TABLE T09D_TIPO_AJUSTE;

DROP TABLE T09D_TIPO_CONTRATO;

DROP TABLE T09D_TIPO_JORNADA;

DROP TABLE T09D_TIPO_PONTO;

DROP TABLE T09D_TIPO_RUBRICA;

-- End of file.

