-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2025-05-07 18:49:12.65

-- tables
-- Table: T09D_AFASTAMENTO
CREATE TABLE T09D_AFASTAMENTO (
    ID integer  NOT NULL,
    INICIO date  NOT NULL,
    TERMINO date  NOT NULL,
    ID_TIPO integer  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    CONSTRAINT T09D_AFASTAMENTO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_AJUSTE
CREATE TABLE T09D_AJUSTE (
    ID integer  NOT NULL,
    DATA_LANCAMENTO date  NOT NULL,
    QUANTIDADE_HORAS number(6,2)  NOT NULL,
    MOTIVO varchar2(200)  NOT NULL,
    ID_TIPO_AJUSTE integer  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    CONSTRAINT T09D_AJUSTE_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_BAIRRO
CREATE TABLE T09D_BAIRRO (
    ID int  NOT NULL,
    NOME varchar2(50)  NOT NULL,
    MUNICIPIO varchar2(50)  NOT NULL,
    SIGLA_UF char(2)  NOT NULL,
    CONSTRAINT T09D_BAIRRO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_BANCO_DE_HORAS
CREATE TABLE T09D_BANCO_DE_HORAS (
    ID integer  NOT NULL,
    DATA date  NOT NULL,
    SALDO_HORA number(6,2)  NOT NULL,
    ID_REGISTRO_PONTO integer  NOT NULL,
    CONSTRAINT T09D_BANCO_DE_HORAS_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_COMPENSACAO
CREATE TABLE T09D_COMPENSACAO (
    ID integer  NOT NULL,
    DATA date  NOT NULL,
    HORAS_USADAS number(6,2)  NOT NULL,
    JUSTIFICATIVA varchar2(200)  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    CONSTRAINT T09D_COMPENSACAO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_CONTRATO
CREATE TABLE T09D_CONTRATO (
    ID integer  NOT NULL,
    EMPRESA_CONTRATANTE varchar2(100)  NOT NULL,
    INICIO date  NOT NULL,
    TERMINO date  NULL,
    DATA_ADMISSAO date  NOT NULL,
    ATIVO integer  NOT NULL,
    CARGA_HORARIA_SEMANAL number(5,2)  NOT NULL,
    VALOR_MENSAL number(10,2)  NOT NULL,
    ID_TIPO_CONTRATO integer  NOT NULL,
    ID_TIPO_JORNADA integer  NOT NULL,
    CONSTRAINT T09D_CONTRATO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_ENDERECO
CREATE TABLE T09D_ENDERECO (
    ID int  NOT NULL,
    LOGRADOURO varchar2(50)  NOT NULL,
    COMPLEMENTO varchar2(100)  NOT NULL,
    NUMERO_CASA int  NOT NULL,
    NUMERO_CEP int  NOT NULL,
    ID_BAIRRO int  NOT NULL,
    CONSTRAINT T09D_ENDERECO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_ESCALA
CREATE TABLE T09D_ESCALA (
    ID integer  NOT NULL,
    DATA date  NOT NULL,
    INICIO timestamp  NOT NULL,
    TERMINO timestamp  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    CONSTRAINT T09D_ESCALA_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_ESPECIALIZACAO
CREATE TABLE T09D_ESPECIALIZACAO (
    ID integer  NOT NULL,
    NOME varchar2(100)  NOT NULL,
    CONSTRAINT T09D_ESPECIALIZACAO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_EVENTO_PAGAMENTO
CREATE TABLE T09D_EVENTO_PAGAMENTO (
    ID integer  NOT NULL,
    DESCRICAO varchar2(200)  NOT NULL,
    ID_FORMA_PAGAMENTO integer  NOT NULL,
    ID_RUBRICA integer  NOT NULL,
    ID_REGISTRO_PONTO integer  NOT NULL,
    ID_BANCO_HORAS integer  NOT NULL,
    ID_AFASTAMENTO integer  NOT NULL,
    CONSTRAINT T09D_EVENTO_PAGAMENTO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_FERIAS
CREATE TABLE T09D_FERIAS (
    ID integer  NOT NULL,
    INICIO date  NOT NULL,
    FIM date  NOT NULL,
    SALDO_DIAS number(5,2)  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    CONSTRAINT T09D_FERIAS_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_FORMACAO
CREATE TABLE T09D_FORMACAO (
    ID integer  NOT NULL,
    INSTITUICAO varchar2(100)  NOT NULL,
    INICIO date  NOT NULL,
    FIM date  NOT NULL,
    NIVEL varchar2(100)  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    CONSTRAINT T09D_FORMACAO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_FORMA_DE_PAGAMENTO
CREATE TABLE T09D_FORMA_DE_PAGAMENTO (
    ID integer  NOT NULL,
    DESCRICAO varchar2(50)  NOT NULL,
    CONSTRAINT T09D_FORMA_DE_PAGAMENTO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_OCUPACAO
CREATE TABLE T09D_OCUPACAO (
    ID integer  NOT NULL,
    NUMERO_LEITO integer  NOT NULL,
    ENTRADA date  NOT NULL,
    SAIDA date  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    ID_PACIENTE integer  NOT NULL,
    CONSTRAINT T09D_OCUPACAO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_PACIENTE
CREATE TABLE T09D_PACIENTE (
    ID integer  NOT NULL,
    NOME varchar2(100)  NOT NULL,
    ENTRADA date  NOT NULL,
    SAIDA date  NOT NULL,
    SITUACAO varchar2(100)  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    CONSTRAINT T09D_PACIENTE_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_PONTO
CREATE TABLE T09D_PONTO (
    ID integer  NOT NULL,
    ENTRADA date  NOT NULL,
    SAIDA date  NOT NULL,
    ID_TIPO_PONTO integer  NOT NULL,
    CONSTRAINT T09D_PONTO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_PROFISSIONAL
CREATE TABLE T09D_PROFISSIONAL (
    ID integer  NOT NULL,
    NOME varchar2(200)  NOT NULL,
    TELEFONE varchar2(20)  NOT NULL,
    CPF varchar2(11)  NOT NULL,
    CRM varchar2(50)  NOT NULL,
    DATA_NASCIMENTO date  NOT NULL,
    ID_ENDERECO int  NOT NULL,
    ID_SETOR integer  NOT NULL,
    ID_CONTRADO integer  NOT NULL,
    CONSTRAINT T09D_PROFISSIONAL_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_PROFISSIONAL_ESPEC
CREATE TABLE T09D_PROFISSIONAL_ESPEC (
    ID integer  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    ID_ESPECIALIZACAO integer  NOT NULL,
    CONSTRAINT T09D_PROFISSIONAL_ESPEC_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_REGISTRO_DE_PONTO
CREATE TABLE T09D_REGISTRO_DE_PONTO (
    ID integer  NOT NULL,
    DATA date  NOT NULL,
    OBSERVACOES varchar2(200)  NOT NULL,
    ID_AJUSTE integer  NOT NULL,
    ID_COMPOSICAO integer  NOT NULL,
    ID_PONTO integer  NOT NULL,
    ID_PROFISSIONAL integer  NOT NULL,
    ID_ESCALA integer  NOT NULL,
    ID_FERIAS integer  NOT NULL,
    CONSTRAINT T09D_REGISTRO_DE_PONTO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_RUBRICA
CREATE TABLE T09D_RUBRICA (
    ID integer  NOT NULL,
    DESCRICAO varchar2(200)  NOT NULL,
    ID_TIPO_RUBRICA integer  NOT NULL,
    CONSTRAINT T09D_RUBRICA_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_SETOR
CREATE TABLE T09D_SETOR (
    ID integer  NOT NULL,
    NOME varchar2(50)  NOT NULL,
    CONSTRAINT T09D_SETOR_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_TIPO_AFASTAMENTO
CREATE TABLE T09D_TIPO_AFASTAMENTO (
    ID integer  NOT NULL,
    DESCRICAO varchar2(100)  NOT NULL,
    CONSTRAINT T09D_TIPO_AFASTAMENTO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_TIPO_AJUSTE
CREATE TABLE T09D_TIPO_AJUSTE (
    ID integer  NOT NULL,
    DESCRICAO varchar2(200)  NOT NULL,
    CONSTRAINT T09D_TIPO_AJUSTE_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_TIPO_CONTRATO
CREATE TABLE T09D_TIPO_CONTRATO (
    ID integer  NOT NULL,
    NOME varchar2(100)  NOT NULL,
    CONSTRAINT T09D_TIPO_CONTRATO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_TIPO_JORNADA
CREATE TABLE T09D_TIPO_JORNADA (
    ID integer  NOT NULL,
    NOME varchar2(50)  NOT NULL,
    CONSTRAINT T09D_TIPO_JORNADA_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_TIPO_PONTO
CREATE TABLE T09D_TIPO_PONTO (
    ID integer  NOT NULL,
    DESCRICAO varchar2(50)  NOT NULL,
    CONSTRAINT T09D_TIPO_PONTO_pk PRIMARY KEY (ID)
) ;

-- Table: T09D_TIPO_RUBRICA
CREATE TABLE T09D_TIPO_RUBRICA (
    ID integer  NOT NULL,
    DESCRICAO_TIPO varchar2(200)  NOT NULL,
    CONSTRAINT T09D_TIPO_RUBRICA_pk PRIMARY KEY (ID)
) ;

-- foreign keys
-- Reference: AFASTAMENTO_PROFISSIONAL (table: T09D_AFASTAMENTO)
ALTER TABLE T09D_AFASTAMENTO ADD CONSTRAINT AFASTAMENTO_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: COMPENSACAO_PROFISSIONAL (table: T09D_COMPENSACAO)
ALTER TABLE T09D_COMPENSACAO ADD CONSTRAINT COMPENSACAO_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: CONTRATO_JORNADA (table: T09D_CONTRATO)
ALTER TABLE T09D_CONTRATO ADD CONSTRAINT CONTRATO_JORNADA
    FOREIGN KEY (ID_TIPO_JORNADA)
    REFERENCES T09D_TIPO_JORNADA (ID);

-- Reference: CONTRATO_TIPO_CONTRATO (table: T09D_CONTRATO)
ALTER TABLE T09D_CONTRATO ADD CONSTRAINT CONTRATO_TIPO_CONTRATO
    FOREIGN KEY (ID_TIPO_CONTRATO)
    REFERENCES T09D_TIPO_CONTRATO (ID);

-- Reference: EVENTO_PAGAMENTO_AFASTAMENTO (table: T09D_EVENTO_PAGAMENTO)
ALTER TABLE T09D_EVENTO_PAGAMENTO ADD CONSTRAINT EVENTO_PAGAMENTO_AFASTAMENTO
    FOREIGN KEY (ID_AFASTAMENTO)
    REFERENCES T09D_AFASTAMENTO (ID);

-- Reference: EVENTO_PAGAMENTO_BANCO (table: T09D_EVENTO_PAGAMENTO)
ALTER TABLE T09D_EVENTO_PAGAMENTO ADD CONSTRAINT EVENTO_PAGAMENTO_BANCO
    FOREIGN KEY (ID_BANCO_HORAS)
    REFERENCES T09D_BANCO_DE_HORAS (ID);

-- Reference: FORMACAO_PROFISSIONAL (table: T09D_FORMACAO)
ALTER TABLE T09D_FORMACAO ADD CONSTRAINT FORMACAO_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: OCUPACAO_PROFISSIONAL (table: T09D_OCUPACAO)
ALTER TABLE T09D_OCUPACAO ADD CONSTRAINT OCUPACAO_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: PACIENTE_PROFISSIONAL (table: T09D_PACIENTE)
ALTER TABLE T09D_PACIENTE ADD CONSTRAINT PACIENTE_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: PONTO_TIPO_PONTO (table: T09D_PONTO)
ALTER TABLE T09D_PONTO ADD CONSTRAINT PONTO_TIPO_PONTO
    FOREIGN KEY (ID_TIPO_PONTO)
    REFERENCES T09D_TIPO_PONTO (ID);

-- Reference: PROFISSIONAL_CONTRATO (table: T09D_PROFISSIONAL)
ALTER TABLE T09D_PROFISSIONAL ADD CONSTRAINT PROFISSIONAL_CONTRATO
    FOREIGN KEY (ID_CONTRADO)
    REFERENCES T09D_CONTRATO (ID);

-- Reference: PROFISSIONAL_ENDERECO (table: T09D_PROFISSIONAL)
ALTER TABLE T09D_PROFISSIONAL ADD CONSTRAINT PROFISSIONAL_ENDERECO
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES T09D_ENDERECO (ID);

-- Reference: PROFISSIONAL_ESPECIALIZACAO (table: T09D_PROFISSIONAL_ESPEC)
ALTER TABLE T09D_PROFISSIONAL_ESPEC ADD CONSTRAINT PROFISSIONAL_ESPECIALIZACAO
    FOREIGN KEY (ID_ESPECIALIZACAO)
    REFERENCES T09D_ESPECIALIZACAO (ID);

-- Reference: PROFISSIONAL_ESPEC_PROF (table: T09D_PROFISSIONAL_ESPEC)
ALTER TABLE T09D_PROFISSIONAL_ESPEC ADD CONSTRAINT PROFISSIONAL_ESPEC_PROF
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: REGISTRO_DE_PONTO_ESCALA (table: T09D_REGISTRO_DE_PONTO)
ALTER TABLE T09D_REGISTRO_DE_PONTO ADD CONSTRAINT REGISTRO_DE_PONTO_ESCALA
    FOREIGN KEY (ID_ESCALA)
    REFERENCES T09D_ESCALA (ID);

-- Reference: REGISTRO_DE_PONTO_FERIAS (table: T09D_REGISTRO_DE_PONTO)
ALTER TABLE T09D_REGISTRO_DE_PONTO ADD CONSTRAINT REGISTRO_DE_PONTO_FERIAS
    FOREIGN KEY (ID_FERIAS)
    REFERENCES T09D_FERIAS (ID);

-- Reference: REGISTRO_DE_PONTO_PROFISSIONAL (table: T09D_REGISTRO_DE_PONTO)
ALTER TABLE T09D_REGISTRO_DE_PONTO ADD CONSTRAINT REGISTRO_DE_PONTO_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: T09D_AJUSTE_T09D_PROFISSIONAL (table: T09D_AJUSTE)
ALTER TABLE T09D_AJUSTE ADD CONSTRAINT T09D_AJUSTE_T09D_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: T09D_AJUSTE_T09D_TIPO_AJUSTE (table: T09D_AJUSTE)
ALTER TABLE T09D_AJUSTE ADD CONSTRAINT T09D_AJUSTE_T09D_TIPO_AJUSTE
    FOREIGN KEY (ID_TIPO_AJUSTE)
    REFERENCES T09D_TIPO_AJUSTE (ID);

-- Reference: T09D_ENDERECO_T09D_BAIRRO (table: T09D_ENDERECO)
ALTER TABLE T09D_ENDERECO ADD CONSTRAINT T09D_ENDERECO_T09D_BAIRRO
    FOREIGN KEY (ID_BAIRRO)
    REFERENCES T09D_BAIRRO (ID);

-- Reference: T09D_ESCALA_T09D_PROFISSIONAL (table: T09D_ESCALA)
ALTER TABLE T09D_ESCALA ADD CONSTRAINT T09D_ESCALA_T09D_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: T09D_FERIAS_T09D_PROFISSIONAL (table: T09D_FERIAS)
ALTER TABLE T09D_FERIAS ADD CONSTRAINT T09D_FERIAS_T09D_PROFISSIONAL
    FOREIGN KEY (ID_PROFISSIONAL)
    REFERENCES T09D_PROFISSIONAL (ID);

-- Reference: T09D_OCUPACAO_T09D_PACIENTE (table: T09D_OCUPACAO)
ALTER TABLE T09D_OCUPACAO ADD CONSTRAINT T09D_OCUPACAO_T09D_PACIENTE
    FOREIGN KEY (ID_PACIENTE)
    REFERENCES T09D_PACIENTE (ID);

-- Reference: T09D_PROFISSIONAL_T09D_SETOR (table: T09D_PROFISSIONAL)
ALTER TABLE T09D_PROFISSIONAL ADD CONSTRAINT T09D_PROFISSIONAL_T09D_SETOR
    FOREIGN KEY (ID_SETOR)
    REFERENCES T09D_SETOR (ID);

-- Reference: T09D_RUBRICA_T09D_TIPO_RUBRICA (table: T09D_RUBRICA)
ALTER TABLE T09D_RUBRICA ADD CONSTRAINT T09D_RUBRICA_T09D_TIPO_RUBRICA
    FOREIGN KEY (ID_TIPO_RUBRICA)
    REFERENCES T09D_TIPO_RUBRICA (ID);

-- Reference: afastamento_tipo_afastamento (table: T09D_AFASTAMENTO)
ALTER TABLE T09D_AFASTAMENTO ADD CONSTRAINT afastamento_tipo_afastamento
    FOREIGN KEY (ID_TIPO)
    REFERENCES T09D_TIPO_AFASTAMENTO (ID);

-- Reference: banco_horas_registro_ponto (table: T09D_BANCO_DE_HORAS)
ALTER TABLE T09D_BANCO_DE_HORAS ADD CONSTRAINT banco_horas_registro_ponto
    FOREIGN KEY (ID_REGISTRO_PONTO)
    REFERENCES T09D_REGISTRO_DE_PONTO (ID);

-- Reference: evento_forma_pagamento (table: T09D_EVENTO_PAGAMENTO)
ALTER TABLE T09D_EVENTO_PAGAMENTO ADD CONSTRAINT evento_forma_pagamento
    FOREIGN KEY (ID_FORMA_PAGAMENTO)
    REFERENCES T09D_FORMA_DE_PAGAMENTO (ID);

-- Reference: evento_pagamento_reg_ponto (table: T09D_EVENTO_PAGAMENTO)
ALTER TABLE T09D_EVENTO_PAGAMENTO ADD CONSTRAINT evento_pagamento_reg_ponto
    FOREIGN KEY (ID_REGISTRO_PONTO)
    REFERENCES T09D_REGISTRO_DE_PONTO (ID);

-- Reference: evento_pagamento_rubrica (table: T09D_EVENTO_PAGAMENTO)
ALTER TABLE T09D_EVENTO_PAGAMENTO ADD CONSTRAINT evento_pagamento_rubrica
    FOREIGN KEY (ID_RUBRICA)
    REFERENCES T09D_RUBRICA (ID);

-- Reference: ponto_registro_ponto (table: T09D_REGISTRO_DE_PONTO)
ALTER TABLE T09D_REGISTRO_DE_PONTO ADD CONSTRAINT ponto_registro_ponto
    FOREIGN KEY (ID_PONTO)
    REFERENCES T09D_PONTO (ID);

-- Reference: registro_ponto_ajuste (table: T09D_REGISTRO_DE_PONTO)
ALTER TABLE T09D_REGISTRO_DE_PONTO ADD CONSTRAINT registro_ponto_ajuste
    FOREIGN KEY (ID_AJUSTE)
    REFERENCES T09D_AJUSTE (ID);

-- Reference: registro_ponto_compensacao (table: T09D_REGISTRO_DE_PONTO)
ALTER TABLE T09D_REGISTRO_DE_PONTO ADD CONSTRAINT registro_ponto_compensacao
    FOREIGN KEY (ID_COMPOSICAO)
    REFERENCES T09D_COMPENSACAO (ID);

-- End of file.

