-- consultas

-- 2.ver profissionais por especialização
SELECT P.NOME, E.NOME AS ESPECIALIZACAO
FROM T09D_PROFISSIONAL P
JOIN T09D_PROFISSIONAL_ESPEC PE ON P.ID = PE.ID_PROFISSIONAL
JOIN T09D_ESPECIALIZACAO E ON PE.ID_ESPECIALIZACAO = E.ID;

-- 3.escala semanal de profissional
SELECT E.DATA_SEMANA, E.INICIO, E.TERMINO
FROM T09D_ESCALA E
WHERE E.ID_PROFISSIONAL = ID_PROFISSIONAL;

-- 4.ver registro de ponto por data
SELECT r.id_profissional, R.DATA_REGISTRO, P.REGISTRO
FROM T09D_REGISTRO_DE_PONTO R
JOIN T09D_PONTO P ON R.ID_PONTO = P.ID
WHERE R.ID_PROFISSIONAL = ID_PROFISSIONAL
ORDER BY R.DATA_REGISTRO DESC;

-- 5.ver ajustes
-- ver sobre o horário
SELECT A.DATA_LANCAMENTO, A.QUANTIDADE_HORAS, TA.DESCRICAO
FROM T09D_AJUSTE A
JOIN T09D_TIPO_AJUSTE TA ON A.ID_TIPO_AJUSTE = TA.ID
WHERE A.ID_PROFISSIONAL = ID_PROFISSIONAL;

-- 6.ver saldo de horas
SELECT rp.id_profissional, B.DATA_BANCO, B.SALDO_HORA
FROM T09D_BANCO_DE_HORAS B
JOIN T09D_REGISTRO_DE_PONTO RP ON B.ID_REGISTRO_PONTO = RP.ID
WHERE RP.ID_PROFISSIONAL = ID_PROFISSIONAL;

-- 7.consultar ferias agendadas ou já tiradas
SELECT ID_PROFISSIONAL, INICIO, FIM, SALDO_DIAS
FROM T09D_FERIAS
WHERE ID_PROFISSIONAL = ID_PROFISSIONAL;

-- 8.consultar afastamentos
SELECT A.ID_PROFISSIONAL, A.INICIO, A.TERMINO, T.DESCRICAO
FROM T09D_AFASTAMENTO A
JOIN T09D_TIPO_AFASTAMENTO T ON A.ID_TIPO = T.ID
WHERE A.ID_PROFISSIONAL = ID_PROFISSIONAL;

-- 9.ver pacientes sob cuidado de um profissional
SELECT NOME, ENTRADA, SAIDA, SITUACAO, ID_PROFISSIONAL
FROM T09D_PACIENTE
WHERE ID_PROFISSIONAL = ID_PROFISSIONAL;

-- 10.ver ocupação de leitos por profissional
-- Rever select para contemplar total de pacientes por profissional
SELECT O.NUMERO_LEITO, O.ENTRADA, O.SAIDA, P.NOME AS PACIENTE
FROM T09D_OCUPACAO O
JOIN T09D_PACIENTE P ON O.ID_PACIENTE = P.ID
WHERE O.ID_PROFISSIONAL = P.ID_PROFISSIONAL;

-- 11.consultar eventos de pagamento relacionados a um profissional
SELECT E.DESCRICAO, FP.DESCRICAO AS FORMA_PAGAMENTO, R.DESCRICAO AS RUBRICA
FROM T09D_EVENTO_PAGAMENTO E
JOIN T09D_FORMA_DE_PAGAMENTO FP ON E.ID_FORMA_PAGAMENTO = FP.ID
JOIN T09D_RUBRICA R ON E.ID_RUBRICA = R.ID
JOIN T09D_REGISTRO_DE_PONTO RP ON E.ID_REGISTRO_PONTO = RP.ID
WHERE RP.ID_PROFISSIONAL = ID_PROFISSIONAL;

-- 12.ver detalhes contratuais de um profissional
-- VERIFICAR 
SELECT C.EMPRESA_CONTRATANTE, C.INICIO, C.TERMINO, TC.NOME AS TIPO_CONTRATO, TJ.NOME AS TIPO_JORNADA
FROM T09D_CONTRATO C
JOIN T09D_TIPO_CONTRATO TC ON C.ID_TIPO_CONTRATO = TC.ID
JOIN T09D_TIPO_JORNADA TJ ON C.ID_TIPO_JORNADA = TJ.ID
WHERE C.ID = :ID_CONTRATO;

-- 13.jornada de trabalho real vs prevista
-- VERIFICAR
SELECT 
    P.NOME,
    E.DATA_SEMANA,
    E.INICIO AS INICIO_ESCALA,
    E.TERMINO AS TERMINO_ESCALA,
    PT.REGISTRO AS HORA_REGISTRADA
FROM T09D_PROFISSIONAL P
JOIN T09D_ESCALA E ON P.ID = E.ID_PROFISSIONAL
JOIN T09D_REGISTRO_DE_PONTO RP ON RP.ID_ESCALA = E.ID
JOIN T09D_PONTO PT ON PT.ID = RP.ID_PONTO
WHERE E.DATA_SEMANA BETWEEN :DATA_INICIO AND :DATA_FIM;

-- 14.relatório de banco de horas com compensações associadas
SELECT 
    P.NOME,
    BH.DATA_BANCO,
    BH.SALDO_HORA,
    C.DATA_COMPENSACAO,
    C.HORAS_USADAS,
    C.JUSTIFICATIVA
FROM T09D_PROFISSIONAL P
JOIN T09D_REGISTRO_DE_PONTO RP ON P.ID = RP.ID_PROFISSIONAL
JOIN T09D_BANCO_DE_HORAS BH ON BH.ID_REGISTRO_PONTO = RP.ID
JOIN T09D_COMPENSACAO C ON BH.ID_COMPENSACAO = C.ID
ORDER BY BH.DATA_BANCO DESC;

-- 15. pagamentos efetuados relacionados a eventos de ponto, banco de horas e afastamentos
-- VERIFICAR
SELECT 
    P.NOME,
    E.DESCRICAO AS EVENTO,
    R.DESCRICAO AS RUBRICA,
    FP.DESCRICAO AS FORMA_PAGAMENTO,
    A.INICIO AS AFASTAMENTO_INICIO,
    A.TERMINO AS AFASTAMENTO_TERMINO
FROM T09D_EVENTO_PAGAMENTO E
JOIN T09D_FORMA_DE_PAGAMENTO FP ON E.ID_FORMA_PAGAMENTO = FP.ID
JOIN T09D_RUBRICA R ON E.ID_RUBRICA = R.ID
JOIN T09D_REGISTRO_DE_PONTO RP ON E.ID_REGISTRO_PONTO = RP.ID
JOIN T09D_PROFISSIONAL P ON RP.ID_PROFISSIONAL = P.ID
JOIN T09D_AFASTAMENTO A ON E.ID_AFASTAMENTO = A.ID
WHERE A.TERMINO IS NULL OR A.TERMINO >= SYSDATE;

-- 16.relação completa de todos profissionais
SELECT 
    P.NOME, P.EMAIL, P.TELEFONE, P.CPF,
    E.LOGRADOURO || ', ' || E.NUMERO_CASA AS ENDERECO,
    B.NOME AS BAIRRO, B.MUNICIPIO, B.SIGLA_UF,
    C.EMPRESA_CONTRATANTE, C.DATA_ADMISSAO, TC.NOME AS TIPO_CONTRATO,
    S.NOME AS SETOR
FROM T09D_PROFISSIONAL P
JOIN T09D_ENDERECO E ON P.ID_ENDERECO = E.ID
JOIN T09D_BAIRRO B ON E.ID_BAIRRO = B.ID
JOIN T09D_CONTRATO C ON P.ID_CONTRATO = C.ID
JOIN T09D_TIPO_CONTRATO TC ON C.ID_TIPO_CONTRATO = TC.ID
JOIN T09D_SETOR S ON P.ID_SETOR = S.ID;

-- 17.histórico educacional dos profissionais com especializações
SELECT 
    P.NOME,
    F.DESCRICAO AS FORMACAO,
    F.INSTITUICAO,
    F.INICIO,
    F.FIM,
    E.NOME AS ESPECIALIZACAO
FROM T09D_PROFISSIONAL P
LEFT JOIN T09D_FORMACAO F ON P.ID = F.ID_PROFISSIONAL
LEFT JOIN T09D_PROFISSIONAL_ESPEC PE ON P.ID = PE.ID_PROFISSIONAL
LEFT JOIN T09D_ESPECIALIZACAO E ON PE.ID_ESPECIALIZACAO = E.ID;

-- 18.pacientes, leitos, situação e profissional responsável
SELECT 
    PAC.NOME AS PACIENTE,
    PAC.ENTRADA,
    PAC.SITUACAO,
    O.NUMERO_LEITO,
    P.NOME AS PROFISSIONAL_RESPONSAVEL
FROM T09D_OCUPACAO O
JOIN T09D_PACIENTE PAC ON O.ID_PACIENTE = PAC.ID
JOIN T09D_PROFISSIONAL P ON O.ID_PROFISSIONAL = P.ID;

-- -- 19.profissionais com jornadas irregulares ou faltas
-- rever situação para jornadas 12x36
SELECT 
    P.NOME,
    E.DATA_SEMANA,
    E.INICIO,
    E.TERMINO    
FROM T09D_ESCALA E
JOIN T09D_PROFISSIONAL P ON E.ID_PROFISSIONAL = P.ID
LEFT JOIN T09D_REGISTRO_DE_PONTO RP ON RP.ID_ESCALA = E.ID
WHERE RP.ID IS NULL;  -- Não houve registro de ponto

-- 20. consulta geral de eventos de pagamento por profissional
-- verificar
SELECT 
    P.NOME AS PROFISSIONAL,
    RP.DATA_REGISTRO,
    BH.SALDO_HORA,
    R.DESCRICAO AS RUBRICA,
    FP.DESCRICAO AS FORMA_PAGAMENTO,
    EP.DESCRICAO AS EVENTO,
    A.INICIO AS AFASTAMENTO_INICIO,
    A.TERMINO AS AFASTAMENTO_TERMINO
FROM T09D_EVENTO_PAGAMENTO EP
JOIN T09D_FORMA_DE_PAGAMENTO FP ON EP.ID_FORMA_PAGAMENTO = FP.ID
JOIN T09D_RUBRICA R ON EP.ID_RUBRICA = R.ID
JOIN T09D_REGISTRO_DE_PONTO RP ON EP.ID_REGISTRO_PONTO = RP.ID
JOIN T09D_PROFISSIONAL P ON RP.ID_PROFISSIONAL = P.ID
JOIN T09D_BANCO_DE_HORAS BH ON EP.ID_BANCO_HORAS = BH.ID
JOIN T09D_AFASTAMENTO A ON EP.ID_AFASTAMENTO = A.ID
WHERE RP.DATA_REGISTRO BETWEEN TO_DATE('2025-04-01', 'YYYY-MM-DD') AND TO_DATE('2025-04-30', 'YYYY-MM-DD')
ORDER BY P.NOME, RP.DATA_REGISTRO;

-- 21.total de horas acumuladas no banco de horas no mês, por profissional
SELECT 
    P.NOME,
    SUM(BH.SALDO_HORA) AS TOTAL_HORAS_MES
FROM T09D_BANCO_DE_HORAS BH
JOIN T09D_REGISTRO_DE_PONTO RP ON BH.ID_REGISTRO_PONTO = RP.ID
JOIN T09D_PROFISSIONAL P ON RP.ID_PROFISSIONAL = P.ID
WHERE BH.DATA_BANCO BETWEEN TO_DATE('2025-04-01', 'YYYY-MM-DD') AND TO_DATE('2025-04-30', 'YYYY-MM-DD')
GROUP BY P.NOME
ORDER BY P.NOME;

-- 22.detalhamento de rubricas utilizadas em pagamentos no período
SELECT 
    P.NOME AS PROFISSIONAL,
    R.DESCRICAO AS RUBRICA,
    COUNT(*) AS QTD_EVENTOS,
    SUM(BH.SALDO_HORA) AS TOTAL_HORAS
FROM T09D_EVENTO_PAGAMENTO EP
JOIN T09D_RUBRICA R ON EP.ID_RUBRICA = R.ID
JOIN T09D_BANCO_DE_HORAS BH ON EP.ID_BANCO_HORAS = BH.ID
JOIN T09D_REGISTRO_DE_PONTO RP ON EP.ID_REGISTRO_PONTO = RP.ID
JOIN T09D_PROFISSIONAL P ON RP.ID_PROFISSIONAL = P.ID
WHERE BH.DATA_BANCO BETWEEN TO_DATE('2025-04-01', 'YYYY-MM-DD') AND TO_DATE('2025-04-30', 'YYYY-MM-DD')
GROUP BY P.NOME, R.DESCRICAO
ORDER BY P.NOME, R.DESCRICAO;

-- 23. folha sintética: Total de horas e forma de pagamento por profissional
SELECT 
    P.NOME,
    FP.DESCRICAO AS FORMA_PAGAMENTO,
    SUM(BH.SALDO_HORA) AS TOTAL_HORAS
FROM T09D_EVENTO_PAGAMENTO EP
JOIN T09D_FORMA_DE_PAGAMENTO FP ON EP.ID_FORMA_PAGAMENTO = FP.ID
JOIN T09D_BANCO_DE_HORAS BH ON EP.ID_BANCO_HORAS = BH.ID
JOIN T09D_REGISTRO_DE_PONTO RP ON EP.ID_REGISTRO_PONTO = RP.ID
JOIN T09D_PROFISSIONAL P ON RP.ID_PROFISSIONAL = P.ID
WHERE RP.DATA_REGISTRO BETWEEN TO_DATE('2025-04-01', 'YYYY-MM-DD') AND TO_DATE('2025-04-30', 'YYYY-MM-DD')
GROUP BY P.NOME, FP.DESCRICAO
ORDER BY P.NOME;

-- 24. apuração de horas extras por profissional
SELECT 
    P.NOME,
    C.CARGA_HORARIA_SEMANAL,
    SUM(EXTRACT(HOUR FROM (PT.REGISTRO - E.INICIO)) + 
        EXTRACT(MINUTE FROM (PT.REGISTRO - E.INICIO))/60) AS HORAS_TRABALHADAS
FROM T09D_PROFISSIONAL P
JOIN T09D_CONTRATO C ON P.ID_CONTRATO = C.ID
JOIN T09D_ESCALA E ON P.ID = E.ID_PROFISSIONAL
JOIN T09D_REGISTRO_DE_PONTO RP ON RP.ID_ESCALA = E.ID
JOIN T09D_PONTO PT ON PT.ID = RP.ID_PONTO
WHERE E.DATA_SEMANA BETWEEN :DATA_INICIO AND :DATA_FIM
GROUP BY P.NOME, C.CARGA_HORARIA_SEMANAL
HAVING SUM(EXTRACT(HOUR FROM (PT.REGISTRO - E.INICIO)) + 
           EXTRACT(MINUTE FROM (PT.REGISTRO - E.INICIO))/60) > MAX(C.CARGA_HORARIA_SEMANAL);

-- 25.profissionais com múltiplas especializações
SELECT 
    P.NOME,
    COUNT(PE.ID_ESPECIALIZACAO) AS QTD_ESPECIALIZACOES
FROM T09D_PROFISSIONAL P
JOIN T09D_PROFISSIONAL_ESPEC PE ON P.ID = PE.ID_PROFISSIONAL
GROUP BY P.NOME
HAVING COUNT(PE.ID_ESPECIALIZACAO) > 1
ORDER BY QTD_ESPECIALIZACOES DESC;

-- 26.profissionais com o maior número de registros de pontos
SELECT 
    P.NOME,
    COUNT(RP.ID) AS TOTAL_REGISTROS
FROM T09D_PROFISSIONAL P
JOIN T09D_REGISTRO_DE_PONTO RP ON P.ID = RP.ID_PROFISSIONAL
WHERE RP.DATA_REGISTRO BETWEEN TO_DATE('2025-04-01', 'YYYY-MM-DD') AND TO_DATE('2025-04-30', 'YYYY-MM-DD')
GROUP BY P.NOME
ORDER BY TOTAL_REGISTROS DESC;

-- 27.relatório de ausência injustificada
SELECT 
    P.NOME,
    E.DATA_SEMANA,
    E.INICIO,
    E.TERMINO
FROM T09D_PROFISSIONAL P
JOIN T09D_ESCALA E ON P.ID = E.ID_PROFISSIONAL
LEFT JOIN T09D_REGISTRO_DE_PONTO RP ON RP.ID_ESCALA = E.ID
LEFT JOIN T09D_AFASTAMENTO A ON A.ID_PROFISSIONAL = P.ID AND E.DATA_SEMANA BETWEEN A.INICIO AND A.TERMINO
LEFT JOIN T09D_FERIAS F ON F.ID_PROFISSIONAL = P.ID AND E.DATA_SEMANA BETWEEN F.INICIO AND F.FIM
WHERE RP.ID IS NULL AND A.ID IS NULL AND F.ID IS NULL
AND E.DATA_SEMANA BETWEEN TO_DATE('2025-04-01', 'YYYY-MM-DD') AND TO_DATE('2025-04-30', 'YYYY-MM-DD');

-- 28.análise de uso de compensações vs saldo de banco de horas
SELECT 
    P.NOME,
    SUM(BH.SALDO_HORA) AS TOTAL_BANCO,
    SUM(C.HORAS_USADAS) AS TOTAL_COMPENSADO,
    (SUM(BH.SALDO_HORA) - SUM(C.HORAS_USADAS)) AS SALDO_ATUAL
FROM T09D_PROFISSIONAL P
JOIN T09D_REGISTRO_DE_PONTO RP ON P.ID = RP.ID_PROFISSIONAL
JOIN T09D_BANCO_DE_HORAS BH ON RP.ID = BH.ID_REGISTRO_PONTO
JOIN T09D_COMPENSACAO C ON BH.ID_COMPENSACAO = C.ID
GROUP BY P.NOME
ORDER BY SALDO_ATUAL DESC;

-- 29. profissionais com contratos vencendo nos próximos 30 dias
SELECT 
    P.NOME,
    C.EMPRESA_CONTRATANTE,
    C.TERMINO
FROM T09D_PROFISSIONAL P
JOIN T09D_CONTRATO C ON P.ID_CONTRATO = C.ID
WHERE C.TERMINO IS NOT NULL AND C.TERMINO <= SYSDATE + 30
ORDER BY C.TERMINO;

-- 30.relatório com todos os dados do profissional e o nome e idade dos pacientes que estão sob cuidado daquele profissional
SELECT 
    P.ID AS PROFISSIONAL_ID,
    P.NOME AS PROFISSIONAL_NOME,
    P.TELEFONE AS PROFISSIONAL_TELEFONE,
    P.EMAIL AS PROFISSIONAL_EMAIL,
    P.CPF AS PROFISSIONAL_CPF,
    E.LOGRADOURO || ', ' || E.NUMERO_CASA AS PROFISSIONAL_ENDERECO,
    B.NOME AS PROFISSIONAL_BAIRRO,
    B.MUNICIPIO AS PROFISSIONAL_MUNICIPIO,
    B.SIGLA_UF AS PROFISSIONAL_UF,
    C.EMPRESA_CONTRATANTE AS PROFISSIONAL_EMPRESA_CONTRATANTE,
    C.DATA_ADMISSAO AS PROFISSIONAL_DATA_ADMISSAO,
    TC.NOME AS PROFISSIONAL_TIPO_CONTRATO,
    S.NOME AS PROFISSIONAL_SETOR,
    
    PAC.ID AS PACIENTE_ID,
    PAC.NOME AS PACIENTE_NOME,
    PAC.SITUACAO AS PACIENTE_SITUACAO,
    PAC.ENTRADA AS PACIENTE_ENTRADA,
    PAC.SAIDA AS PACIENTE_SAIDA,
    
    -- Cálculo da idade do paciente
    FLOOR(MONTHS_BETWEEN(SYSDATE, PAC.DATA_NASCIMENTO) / 12) AS PACIENTE_IDADE

FROM T09D_PROFISSIONAL P
JOIN T09D_ENDERECO E ON P.ID_ENDERECO = E.ID
JOIN T09D_BAIRRO B ON E.ID_BAIRRO = B.ID
JOIN T09D_CONTRATO C ON P.ID_CONTRATO = C.ID
JOIN T09D_TIPO_CONTRATO TC ON C.ID_TIPO_CONTRATO = TC.ID
JOIN T09D_SETOR S ON P.ID_SETOR = S.ID
JOIN T09D_OCUPACAO O ON P.ID = O.ID_PROFISSIONAL
JOIN T09D_PACIENTE PAC ON O.ID_PACIENTE = PAC.ID

WHERE PAC.SITUACAO != 'Alta' -- Apenas pacientes em tratamento ou internados (ajuste conforme a situação)
ORDER BY P.NOME, PAC.NOME;

-- Funcionários que tiveram afastamentos (faltas) e os dias - Funcionou 
SELECT 
    P.ID AS ID_PROFISSIONAL,
    P.NOME,
    A.INICIO,
    A.TERMINO,
    TA.DESCRICAO AS TIPO_AFASTAMENTO
FROM T09D_AFASTAMENTO A
JOIN T09D_PROFISSIONAL P ON A.ID_PROFISSIONAL = P.ID
JOIN T09D_TIPO_AFASTAMENTO TA ON A.ID_TIPO = TA.ID;

-- Funcionários que tiraram férias dentro de um período específico - Funcionou 
SELECT 
    P.ID AS ID_PROFISSIONAL,
    P.NOME,
    F.INICIO,
    F.FIM,
    F.SALDO_DIAS
FROM T09D_FERIAS F
JOIN T09D_PROFISSIONAL P ON F.ID_PROFISSIONAL = P.ID
WHERE F.INICIO BETWEEN TO_DATE('2025-01-01', 'YYYY-MM-DD') 
                   AND TO_DATE('2025-03-31', 'YYYY-MM-DD');

-- Escalas onde o profissional não registrou ponto 
SELECT 
    E.ID_PROFISSIONAL,
    P.NOME,
    E.DATA_SEMANA
FROM T09D_ESCALA E
JOIN T09D_PROFISSIONAL P ON E.ID_PROFISSIONAL = P.ID
LEFT OUTER JOIN T09D_REGISTRO_DE_PONTO RP ON RP.ID_ESCALA = E.ID
WHERE RP.ID IS NULL;

-- Funcionários com ajustes manuais de ponto 
SELECT 
    P.ID AS ID_PROFISSIONAL,
    P.NOME,
    A.DATA_LANCAMENTO,
    A.MOTIVO,
    A.QUANTIDADE_HORAS
FROM T09D_AJUSTE A
JOIN T09D_PROFISSIONAL P ON A.ID_PROFISSIONAL = P.ID;
 

--  consulta banco de horas por profissional
SELECT RP.ID_PROFISSIONAL, RP.ID, RP.DATA_REGISTRO,
       (NVL(AJ.HORAS_POS, 0) - NVL(AJ.HORAS_NEG, 0) - 
           CASE 
               WHEN CT.ID_TIPO_JORNADA = 1 THEN (CT.CARGA_HORARIA_SEMANAL / 5)
               WHEN CT.ID_TIPO_JORNADA = 2 THEN 12 
           END
       ) AS SALDO_HORA
FROM T09D_REGISTRO_DE_PONTO RP
JOIN T09D_PROFISSIONAL PF ON RP.ID_PROFISSIONAL = PF.ID
JOIN T09D_CONTRATO CT ON PF.ID_CONTRATO = CT.ID
JOIN T09D_TIPO_JORNADA TJ ON CT.ID_TIPO_JORNADA = TJ.ID
LEFT JOIN (
    SELECT ID_PROFISSIONAL, DATA_LANCAMENTO,
           SUM(CASE WHEN QUANTIDADE_HORAS > 0 THEN QUANTIDADE_HORAS ELSE 0 END) AS HORAS_POS,
           SUM(CASE WHEN QUANTIDADE_HORAS < 0 THEN ABS(QUANTIDADE_HORAS) ELSE 0 END) AS HORAS_NEG
    FROM T09D_AJUSTE
    GROUP BY ID_PROFISSIONAL, DATA_LANCAMENTO
) AJ ON AJ.ID_PROFISSIONAL = RP.ID_PROFISSIONAL 
AND AJ.DATA_LANCAMENTO = RP.DATA_REGISTRO;

-- saldo de férias
SELECT 
    PF.ID AS ID_PROFISSIONAL, 
    PF.NOME, 
    F.SALDO_DIAS - NVL(AJ.QUANTIDADE_HORAS, 0) AS SALDO_FINAL_FERIAS
FROM T09D_PROFISSIONAL PF
LEFT JOIN T09D_FERIAS F ON PF.ID = F.ID_PROFISSIONAL
LEFT JOIN (
    SELECT ID_PROFISSIONAL, SUM(QUANTIDADE_HORAS) AS QUANTIDADE_HORAS
    FROM T09D_AJUSTE
    GROUP BY ID_PROFISSIONAL
) AJ ON AJ.ID_PROFISSIONAL = PF.ID;