-- Inserção de modalidades de contratos
INSERT INTO T09D_TIPO_CONTRATO (ID, NOME) VALUES (1, 'CLT');
INSERT INTO T09D_TIPO_CONTRATO (ID, NOME) VALUES (2, 'CNPJ');
INSERT INTO T09D_TIPO_CONTRATO (ID, NOME) VALUES (3, 'Freela');
INSERT INTO T09D_TIPO_CONTRATO (ID, NOME) VALUES (4, 'Terceiros');
INSERT INTO T09D_TIPO_CONTRATO (ID, NOME) VALUES (5, 'Estagiário');
INSERT INTO T09D_TIPO_CONTRATO (ID, NOME) VALUES (6, 'Temporário');

-- Inserção de tipo de jornada
INSERT INTO T09D_TIPO_JORNADA (ID, NOME) VALUES (1, '12x36');
INSERT INTO T09D_TIPO_JORNADA (ID, NOME) VALUES (2, 'Jornada Fixa (40h semanais)');
INSERT INTO T09D_TIPO_JORNADA (ID, NOME) VALUES (3, 'Jornada de Plantão');
INSERT INTO T09D_TIPO_JORNADA (ID, NOME) VALUES (4, 'Jornada Flexível');

-- inserção de nível de acesso
INSERT INTO T09D_NIVEL_DE_ACESSO (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO T09D_NIVEL_DE_ACESSO (ID, DESCRICAO) VALUES (2, 'Departamento Pessoal');
INSERT INTO T09D_NIVEL_DE_ACESSO (ID, DESCRICAO) VALUES (3, 'Colaborador');

-- inserção de setores hospitalares
INSERT INTO T09D_SETOR (ID, NOME) VALUES (1, 'Enfermaria');
INSERT INTO T09D_SETOR (ID, NOME) VALUES (2, 'Pronto Atendimento');
INSERT INTO T09D_SETOR (ID, NOME) VALUES (3, 'UTI');
INSERT INTO T09D_SETOR (ID, NOME) VALUES (4, 'Centro Cirúrgico');
INSERT INTO T09D_SETOR (ID, NOME) VALUES (5, 'Maternidade');

-- inserção de tipos de afastamento
INSERT INTO T09D_TIPO_AFASTAMENTO (ID, DESCRICAO) VALUES (1, 'Saúde');
INSERT INTO T09D_TIPO_AFASTAMENTO (ID, DESCRICAO) VALUES (2, 'Acompanhamento de dependentes');
INSERT INTO T09D_TIPO_AFASTAMENTO (ID, DESCRICAO) VALUES (3, 'Licença maternidade');
INSERT INTO T09D_TIPO_AFASTAMENTO (ID, DESCRICAO) VALUES (4, 'Licença paternidade');
INSERT INTO T09D_TIPO_AFASTAMENTO (ID, DESCRICAO) VALUES (5, 'Afastamento por motivos pessoais');

-- inserção de tipos de rubricas
INSERT INTO T09D_TIPO_RUBRICA (ID, DESCRICAO_TIPO) VALUES (1, 'Salário Vencimentos');
INSERT INTO T09D_TIPO_RUBRICA (ID, DESCRICAO_TIPO) VALUES (2, 'Horas Extras');
INSERT INTO T09D_TIPO_RUBRICA (ID, DESCRICAO_TIPO) VALUES (3, 'Férias');
INSERT INTO T09D_TIPO_RUBRICA (ID, DESCRICAO_TIPO) VALUES (4, 'Bonificação');
INSERT INTO T09D_TIPO_RUBRICA (ID, DESCRICAO_TIPO) VALUES (5, 'Comissões');

-- inserção forma de pagamento
INSERT INTO T09D_FORMA_DE_PAGAMENTO (ID, DESCRICAO) VALUES (1, 'Pix');
INSERT INTO T09D_FORMA_DE_PAGAMENTO (ID, DESCRICAO) VALUES (2, 'Transferência');
INSERT INTO T09D_FORMA_DE_PAGAMENTO (ID, DESCRICAO) VALUES (3, 'Cheque');
INSERT INTO T09D_FORMA_DE_PAGAMENTO (ID, DESCRICAO) VALUES (4, 'Depósito em conta');

-- inserção de ajuste
INSERT INTO T09D_TIPO_AJUSTE (ID, DESCRICAO) VALUES (1, 'Correções de atrasos');
INSERT INTO T09D_TIPO_AJUSTE (ID, DESCRICAO) VALUES (2, 'Compensações de horas');
INSERT INTO T09D_TIPO_AJUSTE (ID, DESCRICAO) VALUES (3, 'Correções de marcações incorretas');
INSERT INTO T09D_TIPO_AJUSTE (ID, DESCRICAO) VALUES (4, 'Ajustes por erro de registro');

-- inserção de tipos de pontos
INSERT INTO T09D_TIPO_PONTO (ID, DESCRICAO) VALUES (1, 'Entrada');
INSERT INTO T09D_TIPO_PONTO (ID, DESCRICAO) VALUES (2, 'Saída');

-- inserção de bairros de blumenau
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (1, 'Água Verde', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (2, 'Bom Retiro', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (3, 'Boa Vista', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (4, 'Centro', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (5, 'Do Salto', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (6, 'Escola Agrícola', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (7, 'Fortaleza', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (8, 'Fortaleza Alta', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (9, 'Garcia', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (10, 'Itoupava Central', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (11, 'Itoupava Norte', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (12, 'Itoupava Seca', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (13, 'Nova Esperança', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (14, 'Ponta Aguda', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (15, 'Progresso', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (16, 'Salto do Norte', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (17, 'Salto Weissbach', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (18, 'Testo Salto', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (19, 'Tribess', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (20, 'Velha', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (21, 'Velha Central', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (22, 'Velha Grande', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (23, 'Vila Formosa', 'Blumenau', 'SC');
INSERT INTO T09D_BAIRRO (ID, NOME, MUNICIPIO, SIGLA_UF) VALUES (24, 'Vila Itoupava', 'Blumenau', 'SC');

-- inserção de especializações médicas
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (1, 'Anestesiologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (2, 'Cardiologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (3, 'Cirurgia Geral');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (4, 'Cirurgia Plástica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (5, 'Clínica Médica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (6, 'Dermatologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (7, 'Endocrinologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (8, 'Gastroenterologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (9, 'Geriatria');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (10, 'Ginecologia e Obstetrícia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (11, 'Hematologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (12, 'Infectologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (13, 'Medicina de Família e Comunidade');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (14, 'Medicina do Trabalho');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (15, 'Medicina Esportiva');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (16, 'Nefrologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (17, 'Neurocirurgia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (18, 'Neurologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (19, 'Nutrologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (20, 'Oftalmologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (21, 'Oncologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (22, 'Ortopedia e Traumatologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (23, 'Otorrinolaringologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (24, 'Pediatria');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (25, 'Pneumologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (26, 'Psiquiatria');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (27, 'Radiologia e Diagnóstico por Imagem');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (28, 'Reumatologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (29, 'Urologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (30, 'Patologia Clínica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (31, 'Medicina Intensiva');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (32, 'Medicina Nuclear');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (33, 'Genética Médica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (34, 'Hemodinâmica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (35, 'Mastologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (36, 'Angiologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (37, 'Coloproctologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (38, 'Cirurgia Torácica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (39, 'Cirurgia Vascular');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (40, 'Cirurgia Pediátrica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (41, 'Cirurgia Oncológica');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (42, 'Fisiatria');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (43, 'Medicina Legal');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (44, 'Medicina Preventiva');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (45, 'Saúde da Família');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (46, 'Sexologia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (47, 'Endoscopia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (48, 'Ecocardiografia');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (49, 'Emergencista');
INSERT INTO T09D_ESPECIALIZACAO (ID, NOME) VALUES (50, 'Ginecologia Oncológica');
